"""Images table

Revision ID: 160c252da0c6
Revises: 4da7e245fb77
Create Date: 2020-06-20 18:17:00.844967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '160c252da0c6'
down_revision = '4da7e245fb77'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=256), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('author', sa.String(length=128), nullable=False),
    sa.Column('booktype', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_images_author'), 'images', ['author'], unique=False)
    op.create_index(op.f('ix_images_booktype'), 'images', ['booktype'], unique=False)
    op.create_index(op.f('ix_images_filename'), 'images', ['filename'], unique=True)
    op.create_index(op.f('ix_images_title'), 'images', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_images_title'), table_name='images')
    op.drop_index(op.f('ix_images_filename'), table_name='images')
    op.drop_index(op.f('ix_images_booktype'), table_name='images')
    op.drop_index(op.f('ix_images_author'), table_name='images')
    op.drop_table('images')
    # ### end Alembic commands ###


def upgrade_payments():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_payments():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

